import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About/About'
import Hero from '../components/Hero/Hero'
import HomeTransition from '../Hoc/HomeTransition'

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
    </div>
  )
}

export default HomeTransition(Home);